### ISSUE TITLE
Does this work with Easy Anti-Cheat?

### ISSUE THREAD

**Issue by techsideofficial** [3ddelano/epic-online-services-godot#10]
Does this work with Easy Anti-Cheat?

**Comment by 3ddelano** [comment]
Currently the Anti cheat functions are not implemented in the wrapper but there isn't reason why it shouldn't work.

**Comment by techsideofficial** [comment]
@3ddelano How would I make it work? I am not that experienced with C#.

**Comment by 3ddelano** [comment]
The c# version of the EOS SDK was used for Godot 3 Mono and the wrapper for Godot 3 is deprecated. Right now for Godot 4 we use the EOS C SDK v1.15. The general steps to wrap a new interface like Easy Anti Cheat are the following:
1. Read about the interface in EOS docs
2. List all the functions that need to be wrapped from the EOS C SDK
3. Wrap each function in gdextension so that it is available inGDScript. Refer the previous wrapped interfaces, it will mostly be similar syntax to those. We also have helpful macros to easier convert data structures.
4. Test each function works as expected in GDScript
5. Optionally make a sample scene for the interface with a UI

**Comment by techsideofficial** [comment]
@3ddelano Can I just use it with Godot Mono? I just learned a bit of C#

**Comment by 3ddelano** [comment]
Yes you definitely can! For the Godot mono it saves some time as you can directly code in c#. EOS C# requires a setup function where you initialise the SDK, following which you can then call the interface functions. A good reference would be IEOS.cs script  [initialisation function](https://github.com/3ddelano/epic-online-services-godot/blob/a5e4a996ab1e4c96fb038737f550b1440f3e4a11/EOS/Scripts/IEOS.cs#L179). Also read the Readme.md file of the godot3-mono branch for the installation steps (editing the .csproj, etc).

**Comment by techsideofficial** [comment]
@3ddelano ummmmm `IEOS.cs` 
![image](https://github.com/3ddelano/epic-online-services-godot/assets/68258126/f1a7ca27-ff5f-4f1c-8b60-d52c8d848bd9)

**Comment by 3ddelano** [comment]
What are the steps to reproduce this? Did you follow the installation steps in the readme? Also note this is for Godot 3. I haven't tested it out with Godot 4 where the .NET version was upgraded.

**Comment by techsideofficial** [comment]
@3ddelano That's my project folder: [https://github.com/techsideofficial/XanEngine/tree/main/XanTestProjects/TestProj](url)

**Comment by techsideofficial** [comment]
@3ddelano that's what I'm doing. I'm using Godot 3.5.2 LTS

**Comment by 3ddelano** [comment]
Can you try cloning the repo and running the sample project?

**Comment by techsideofficial** [comment]
@3ddelano The sample project runs fine.

**Comment by 3ddelano** [comment]
Try deleting the .mono folder, sometimes the mono cache gets messed up.

**Comment by techsideofficial** [comment]
I'll try it tomorrow.

**Comment by techsideofficial** [comment]
@3ddelano 
![image](https://github.com/3ddelano/epic-online-services-godot/assets/68258126/a2a0bd66-f045-434d-85d9-69988e763c8a)
![Screenshot 2023-09-09 071842](https://github.com/3ddelano/epic-online-services-godot/assets/68258126/a5bd9ba9-2215-44e3-8298-ea8358d69f9c)

**Comment by 3ddelano** [comment]
The issue is that somehow the project was converted to Godot 4 mono. Did you perhaps run the auto convert the project by opening it in Godot 4 mono?

**Comment by 3ddelano** [comment]
Here 'RefCounted' is from Godot 4 while the Godot 3 equivalent is 'Reference'.

**Comment by 3ddelano** [comment]
To resolve it, replace the existing files with a re-clone of the godot3-mono branch.

**Comment by techsideofficial** [comment]
@3ddelano nvm its fixed. How would I check if the game was launched via anticheat then?

**Comment by techsideofficial** [comment]
How do I check if the game has been launched from EAC?

**Comment by 3ddelano** [comment]
EOS provides protected game session notifications. See this https://dev.epicgames.com/docs/game-services/anti-cheat/using-anti-cheat#protected-game-session-notifications

**Comment by techsideofficial** [comment]
How do I quit the app if it hasn't been launched through EAC?

**Comment by 3ddelano** [comment]
A starting point would be to check out the official anti cheat sample project. https://dev.epicgames.com/docs/game-services/anti-cheat/anti-cheat-samples#step-1-configure-the-samples

**Comment by 3ddelano** [comment]
@techsideofficial Anticheat features are implemented in v2.1.2 https://github.com/3ddelano/epic-online-services-godot/releases/tag/2.1.2
