### ISSUE TITLE
Compiler Error in auth_interface.cpp

### ISSUE THREAD

**Issue by LowFire** [3ddelano/epic-online-services-godot#12]
I pulled the repo and tried compiling it today. I got this compiler error:

> auth_interface.cpp(42): error C2039: 'AccountFeatureRestrictedInfo': is not a member of '_tagEOS_Auth_LoginCallbackInfo'

In the EOS Documentation:

![Capture](https://github.com/3ddelano/epic-online-services-godot/assets/33795345/0bec55e4-b81c-44f2-b349-e7da00861064)

https://dev.epicgames.com/docs/api-ref/structs/eos-auth-login-callback-info

I looked into the eos_auth_typs.h file, and it's still there. It's just been renamed to AccountFeaturesRestrictedInfo_DEPRECATED.

**Comment by 3ddelano** [comment]
Which version of EOS are you using?

**Comment by 3ddelano** [comment]
A version above 1.15 may need changes due to breaking changes or updates.

**Comment by LowFire** [comment]
> Which version of EOS are you using?

I'm using the latest version, which is 1.16.1.

**Comment by 3ddelano** [comment]
Try using v.1.15 for now until the project is updated. Or download the prebuilt addon from the GitHub releases page.

**Comment by 3ddelano** [comment]
Fixed https://github.com/3ddelano/epic-online-services-godot/pull/13
