### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by LowFire** [3ddelano/epic-online-services-godot#19]
Are there any plans to release this plugin for Linux? I can see that the windows binaries are available for download, but what about Linux? I'm asking because my friend and I are running a ci/cd pipeline where we grab the windows binaries every time we export our game for windows. I can build the Linux binaries myself, but I figured it would be a bit easier and save a few steps if we could grab the Linux version of the plugin straight from the git repo instead of me having to build it every time there's an updated version.

**Comment by 3ddelano** [comment]
I though of having a GitHub action to build for windows, Linux and OSX but won't that need putting the EOS SDK code in the repo. I'm unsure about the legality of that.

**Comment by 3ddelano** [comment]
Got it working.
https://github.com/3ddelano/epic-online-services-godot/actions/runs/7206875017

**Comment by LowFire** [comment]
> Got it working. https://github.com/3ddelano/epic-online-services-godot/actions/runs/7206875017

Awesome.  But i'm curious, how did you do it? I had posted on the Epic Games developer forum and I was told that downloading via CLI isn't possible. Are you downloading the sdk via curl? Or using some other method?

Also, apparently it's fine to commit the SDK to a repo so as long as it's a private repo. Here's the post I got:
![Capture](https://github.com/3ddelano/epic-online-services-godot/assets/33795345/3177ba54-14a9-4b42-9e3b-04c5e9f290cd)

**Comment by 3ddelano** [comment]
Yes that's exactly what I did. I made a private GitHub repo with the SDK files. Then made a Personal access token (PAT) for that specific repo with the read repo permission.

Then I added the private repo as a git submodule in the plugin repo. Finally in the in the plugin repo I setup a GitHub action to pull the SDK from the private repo using the PAT and then build the gdextension.
