### ISSUE TITLE
SAMPLE NOT WORKING *PLS FIX* THANK

### ISSUE THREAD

**Issue by samplenotworkingplshelptank** [3ddelano/epic-online-services-godot#25]
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/dfe829a4-d96e-433a-b841-a40d53a5fcd9)
_**WHAT IS THIS BEHAVIOR**_

**Comment by samplenotworkingplshelptank** [comment]
[testosterone.pdf](https://github.com/3ddelano/epic-online-services-godot/files/13850355/testosterone.pdf)
MY \*TERMS\* OF \*SERVICES\*
PLS READ TANK

**Comment by samplenotworkingplshelptank** [comment]
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/1db78e7f-eab8-44c8-8239-d1d0eaa41d51)

**Comment by 3ddelano** [comment]
You have to install the Epic Online Services Godot plugin from the Asset Lib and then enable it in Project Settings. See this repo's Readme

**Comment by samplenotworkingplshelptank** [comment]
sir, it is the demo which you provided

**Comment by samplenotworkingplshelptank** [comment]
https://github.com/3ddelano/epic-online-services-godot/tree/main/sample

**Comment by samplenotworkingplshelptank** [comment]
it was already enabled in the demo

**Comment by 3ddelano** [comment]
It would work if the plugin is installed and enabled. Try to restart the Godot editor.

**Comment by samplenotworkingplshelptank** [comment]
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/b8163efb-0aed-4252-a66e-448c0626c6c8)
new error found pls fix tank

**Comment by 3ddelano** [comment]
What are the exact steps you have done?
Check this steps to get the sample project running. Make sure you use Godot 4.2 too.
https://github.com/3ddelano/epic-online-services-godot?tab=readme-ov-file#how-to-run-the-sample-project

**Comment by samplenotworkingplshelptank** [comment]
> What are the exact steps you have done? Check this steps to get the sample project running
cloned repository (https://github.com/3ddelano/epic-online-services-godot/)
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/b143cd45-5c14-45d9-8b72-61447ba2c29e)
^^ This repository

# imported sample folder in godot

installed the plugin from asset lib
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/83a9a711-57d3-47ea-9b2d-64e8b3aa931a)
# ^^ This plugin

![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/1d3764cf-8aff-4c21-a0f5-39153013f013)
# ^^ Clicked this button

# and that error came

**Comment by samplenotworkingplshelptank** [comment]
made everything a heading for visibility

**Comment by samplenotworkingplshelptank** [comment]
also yes i did not forget to put these values in
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/dea89b76-1260-475b-ba6e-aef73952195a)
![image](https://github.com/3ddelano/epic-online-services-godot/assets/155835180/d3e19f03-e629-4178-af9d-005f3c17b991)

**Comment by 3ddelano** [comment]
Which operating system are you using?

**Comment by 3ddelano** [comment]
Oh I see the issue. The sample in the main branch is updated and new functions are added which are not available in the Released version. To fix this download the sample that matches the commit of the release version. The one for the current latest release is https://github.com/3ddelano/epic-online-services-godot/archive/refs/tags/2.1.0.zip

**Comment by jonathan-robertson** [comment]
Another way to get to the same readme (in case this is more convenient for you, @samplenotworkingplshelptank) would be to switch to that release tag then scroll down to view the README as it was at that tag/release time (see screenshot of how; or here's a [direct link to tag `2.1.0`'s content](https://github.com/3ddelano/epic-online-services-godot/tree/2.1.0))

![image](https://github.com/3ddelano/epic-online-services-godot/assets/5396045/ce517932-a090-4c2f-b954-6b63621772df)
