### ISSUE TITLE
Not an issue, Godot 4.0 Support?

### ISSUE THREAD

**Issue by Starkium** [3ddelano/epic-online-services-godot#6]
Hoping someone else starts a branch for this, otherwise I can take a crack at it. :)

**Comment by 3ddelano** [comment]
Sure go ahead.

**Comment by 3ddelano** [comment]
I have started porting the project to Godot 4 by removing the Godot Mono dependency and shifting the project to GDExtension. The old version will be available on the [godot3-mono](https://github.com/3ddelano/epic-online-services-godot/tree/godot3-mono) branch. I hope to complete the port soon.
