### ISSUE TITLE
BUG: Cannot build with scons

### ISSUE THREAD

**Issue by techsideofficial** [3ddelano/epic-online-services-godot#9]
`C:\Users\wiene\Downloads\epic-online-services-godot-main\epic-online-services-godot-main\thirdparty\eos-sdk\Include\eos_auth_types.h(297): note: see declaration of '_tagEOS_Auth_LoginCallbackInfo'
src\auth_interface.cpp(42): error C2039: '__this': is not a member of '_tagEOS_Auth_LoginCallbackInfo'
C:\Users\wiene\Downloads\epic-online-services-godot-main\epic-online-services-godot-main\thirdparty\eos-sdk\Include\eos_auth_types.h(297): note: see declaration of '_tagEOS_Auth_LoginCallbackInfo'
cl /Fosrc\lobby_search.windows.template_release.x86_64.obj /c src\lobby_search.cpp /TP /std:c++17 /nologo /EHsc /O2 /MD /DTYPED_METHOD_BIND /DNOMINMAX /Igodot-cpp\gdextension /Igodot-cpp\include /Igodot-cpp\gen\include /Isrc /Ithirdparty\eos-sdk\Include
scons: *** [src\auth_interface.windows.template_release.x86_64.obj] Error 2
lobby_search.cpp
scons: building terminated because of errors.`

**Comment by 3ddelano** [comment]
Which version of godot-cpp and the Epic Online Services C SDK are you using?

**Comment by techsideofficial** [comment]
@3ddelano 
`EOS-SDK-27379709-v1.16.1`
And this: [https://github.com/godotengine/godot-cpp/tree/feaba551b5a5b2d13ad1c3fdd8c90e67c67ff37c](url)

**Comment by 3ddelano** [comment]
It might be an issue with EOS v1.16, I have tested with EOS C SDK v.1.5 and godot-cpp for Godot 4.0

**Comment by techsideofficial** [comment]
I'll try that and I'll reopen the issue if I still have problems.
